---
title: "Data Gathering and Cleaning"
author: "Bobby Drysdale"
date: "10/19/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readxl)
library(janitor)
library(reshape2)
```
#All Data Cleaning and Manipulation

##CounterFactual if Gordan Hayward didnt get hurt
```{r}
#First I examined Gordan Hayward's season statistics by year.
##I read in this data from Basketball Reference

haywardstats <- read_excel("gordanhaywardstats.xlsx")

#I get rid of his career totals and clean the variable names

ghperseason <- haywardstats %>% 
  head(n = 9) %>% clean_names()

#To make predictions on what he would have done if he didnt get hurt. We need his totals from the years he was at the jazz

ghtotals <- read_excel("ghtotals.xlsx")

#To predict thge kind of year Gordan Hayward would have had, I use the Simple Projection System (SPS) to calculate it.
## More info in this system can be found here: https://www.basketball-reference.com/about/projections.html

ghnoinjury <- ghtotals %>%
  clean_names() %>% 
  
  #We only need the last three years before he got hurt to preform the prediciton
  
  slice(5:7) %>% 
  
  #Removing unneeded variables
  
  select(-age, -tm, -lg, -g, -gs, -pos)

  #Creating a dataframe to merge with my dataframe in order to calculate predicted totals using spefific weights for each of the previous seasons

preweight <- data.frame(season = c("2014-15", "2015-16", "2016-17"), weights = c(6,3,1))

#I Merge the two datasets together

ghpredict <- merge(ghnoinjury, preweight)

#Giving the following weights to all of his total stats: 2016-17 6 times multiplier, 2015-16 3 times multiplier and 2014-15 a 1 times multiplier

ghpredict <-  ghpredict[, 2:24] * ghpredict[, 25]

#I them add the three seasons together

ghpredict <- ghpredict %>% 
  adorn_totals()

#I take only the total values
ghpredict <- ghpredict %>% 
  slice(4)

ghpredict$mp <- 26903
  
#The next step is to calculate a league average players stats playing the amount of minuetes as Hayward

#First I read in Leaguewide averaged from each year and select the years I need

leagueavg <- read_excel("leaguewide_averages.xlsx", skip = 1) %>%
  slice(3:5) %>% 
  clean_names() %>% 
  select(-rk, -season, -lg, -ht, -wt, -age, -g, -pace, -e_fg_percent, -tov_percent, -orb_percent, -ft_fga, -o_rtg)

# Dividing all the average statisitcs by minuetes played then multiplying by both the season weights we used before and Gordan Haywards Minutes

lgavgmin <- leagueavg %>% 
  select(mp)

leagueavg1 <- leagueavg / lgavgmin$mp

leagueavg1 <- leagueavg1 * preweight$weights

leagueavg1 <- leagueavg1 * ghnoinjury$mp

#I take the total from the three years

leagueavg1 <- leagueavg1 %>% 
  adorn_totals() %>% 
  slice(4)

leagueavg1$mp <- 26903

#Now we scale this figure to 1000 minuetes
##The 26,903 is the weighted total amount of minutes from Gordan Haywards three years prior to injury

leagueavg1 <- (leagueavg1 / 26903) * 1000

#Cleaning stats to keep only ones I want.
leagueavg1 <- leagueavg1 %>% 
  select(-fg_percent, -x3p_percent, -ft_percent)

ghpredict <- ghpredict %>% 
  select(-fg_percent, -x3p_percent, -x2p_percent, -e_fg_percent, -ft_percent, -x2p, -x2pa)

#I now calculate Hayward's projected per-36 minuete value
##This is what he would average if he played 36 minuetes per game. It is the regarded as the standard measure in a basketball game for a starter

gordanfinalpred <- (ghpredict + leagueavg1) / (26903 + 1000) * 36

#The last step for Hayward's Predicted Season would be to take into account his age. 

##The age formula is (28 - age) *0.04 if the player is younger than 28, Hayward was 27

gordanfinalpred <- gordanfinalpred * (1 + ((28-27) * 0.004))

  #I calculate his shooting percentages by simply dividing makes by attempts

gordanfinalpred <- mutate(gordanfinalpred, fg_percent = fg/fga,
    x3p_percent = x3p/x3pa,
    ft_percent = ft / fta)

#Fixing the total stat predictions for Gordan Hayward to not have the the season sum. I do this by taking the 36 min projection and multiplying all stats except shooting percentages by 80 games 

ghpredict2 <- gordanfinalpred[, 17:19]

#
ghpredict <- gordanfinalpred[, 1:16] * 80

ghpredicttotals <- bind_cols(ghpredict, ghpredict2)

#This final dataset is Gordan Hayward's predicted stats for his first year on the Celtics without his injury.
```

##Looking at Gordan Hayward compared to other NBA Players

```{r}
#Before I start to calculate the metrics. I first decide what other players to look at. 

##The first to are both the Predicted Gordan Hayward we just calculated and 2018-2019 Gordan Hayward that is in the middle of his season.

###After that, I decided to choose the players who got an increase in playing time because of his injury, as well as several other NBA players for comparasion purposes.

#First I read in the data of the other players we will be using

allplayers <- read_excel("player_advmetrics.xlsx") %>% clean_names() %>% 
  select(-x2p, -x2pa, -x2p_percent)

#Adding the projected data for Gordan Hayward to the rest of the dataset

allplayers <- bind_rows(allplayers, gordanfinalpred)

#Rounding stats to look better

allplayers[,c(-1,-2,-6,-9,-12)] <- round(allplayers[,c(-1,-2,-6,-9,-12)], 1)

allplayers[,c(6,9,12)] <- round(allplayers[,c(6,9,12)], 3)

#Fixing the NA from the Predicted dataset to show it is gordan hayward and his team

allplayers$player[is.na(allplayers$player)] <- "Predicted Gordan Hayward"

allplayers$tm[is.na(allplayers$tm)] <- "BOS"
```

##Looking into Advanced NBA Metrics

```{r}
#To Compare my Predicted Gordan Hayward to the other NBA players, we need to compute the advanced NBA Metrics

##I will use formulas from several websites to make these calculations. The links to these websites will be provided as they are uses

###First I will calculated percentages such as True shooting percentage. The formulas used can be found here: https://www.fromtherumbleseat.com/pages/advanced-basketball-statistics-formula-sheet

#All the numbers come from Basketball References data on the Boston Celetics team statistics from 2017

##While it would be better with a larger group of players to load in the data, for just one player prediction it is more time effective to just plug them in

gordanadv <- ghpredicttotals %>% 
  transmute(
    poss = .96 * ((fga + tov + .44 * fta - orb)),
    ts_percent = 1611 / (2 * (fga + .475 * fta)), 
    orb_percent = orb / mp / (767+791) * 19805 / 5,
    drb_percent = drb / mp / (2878+2804) * 19805 / 5,
    trb_percent = trb / mp / (3645+3595) * 19805 / 5,
    ast_percent = ast / (((mp / (19805 / 5)) * 3141) - fg),
    stl_percent = stl / ((mp / (19805 / 5)) * 8503.4),
    blk_percent = blk / ((mp / (19805 / 5)) * (6973 - 2270)),
    tov_percent = tov / (fga + .475 * fta + ast + tov),
    usg_percent = 100 * ((fga + 0.44 * fta +tov) * (19805 / 5)) / (26903 * (6975 + 0.44 * 1697 + 1149)), 
    x3par = x3pa / fga,
    
    #League average of x3par
    
lg3par = 0.3368176539
)

gordanadv <- gordanadv %>% 

#After these inital statistics are created. I go on to find teh measures that boil all these numbers into acouple numbers. 

##The first I create is the Box Plus/Minus (BPM). Reading on the BPM can be found here: https://www.basketball-reference.com/about/bpm.html#vorp

mutate(
  
  #I am creating a team adjustment that is needed for the bpm calculation
  
#The numbers you see are coefficents used in the regressions from basketball references website
  
  tmrat = (7*1.2 - 1.615801)/5,
   bpm = (0.123391 * 36) + (0.119597 * orb_percent) + (-0.151287 * drb_percent) + (1.255644 * stl_percent) + (0.531838 * blk_percent) + (-0.305868 * ast_percent) - (0.921292 * tov_percent * usg_percent) + (0.711217 * usg_percent * (1 - tov_percent) * (2 * (ts_percent - 0.52) + (0.017022 * ast_percent) + 0.297639 * (x3par - lg3par) - 0.213485) + 0.725930 * sqrt(ast_percent * trb_percent)) + tmrat,
   obpm = (0.064448 * 36) + (0.211125 * orb_percent) + (-0.107545 * drb_percent) + (0.346513 * stl_percent) + (-0.052476 * blk_percent) + (-0.041787 * ast_percent) - (0.932965 * tov_percent * usg_percent) + (0.687359 * usg_percent * (1 - tov_percent) * (2 * (ts_percent - 0.52) + (0.007952 * ast_percent) + 0.374706 * (x3par - lg3par) + 0.181891) + 0.239862 * sqrt(ast_percent * trb_percent)) + tmrat,
  dbpm = bpm - obpm,
  
  #Now I caclulate Value over Replacement PLayer. This takes the BPM and makes it into a estimation of the player's contribution to the team
  
  vorp = (bpm + 2) * 0.73 * .70 * (80/82),
  
  #The last advanced metrics to compute is win shares. We will do this both with Offensive, Defensive and total Wins shares.
  ows = (ghpredicttotals$pts - (0.92 * 1.037 * gordanadv$poss)) / (0.32 * 106.3 * (96 / 97.3)),
  
  #Before I calculate Defensive winning percentage, other vaules need to be computed for the equation
  ##Full explanations on the formulas and methodology can be found here: https://www.basketball-reference.com/about/ratings.html
  
  dfg = 0.4396959702,
  dor = 0.215590079,
  fmw = (dfg * (1 - dor)) / (dfg * (1 - dor) + (1 - dfg) * dor))

gordanadv <- gordanadv %>% 
  mutate(
  stops1 = 170.6270162101,
  stops2 = (3534 / 19805) * fmw * (1 - 1.07 * dor) + (555 / 19805) * 2891 + (159 / 1618) * 0.4 * 1748 * (1 - (1334 / 1748))^2,
  stopsper = ((stops1 + stops2) * 19805) / (8470.6 * 2891),
  drtg = 103.1 + 0.2 * (100 * 2.7198154631 * (1 - stopsper) - 103.1),
  margd = (2891 / 19805) * 99.95 * (1.08 * (1.037) - ((drtg) / 100)),
  dws = (margd) / (0.32 * 106.3 * (96 / 97.3)),
  ws = ows + dws
) %>% select(-dfg, -dor, -fmw, -stops1, -stops2, -stopsper, - drtg, -margd)


```

